### ISSUE TITLE
Img ration on Safari is broken

### ISSUE THREAD

**Issue by chuanchan1116** [gcobcqwe/HITCON-Point-System-2021#57]
Safari specific bug. The image on Safari will be scaled with fix height and changing width.

**Comment by gcobcqwe** [comment]
![IMG_3821](https://user-images.githubusercontent.com/9248639/142752773-b10da9ff-f5bb-41aa-87a4-89d9a2759ebf.PNG)
![IMG_3820](https://user-images.githubusercontent.com/9248639/142752777-62f6ccb5-9612-4b0b-83d8-50e1136e3d93.PNG)
