### ISSUE TITLE
`req.body.points` is a string by default, causing `/api/v1/users` always fails.

### ISSUE THREAD

**Issue by s3131212** [gcobcqwe/HITCON-Point-System-2021#7]
In [`server/controllers/users.js`](https://github.com/gcobcqwe/HITCON-Point-System-2021/blob/implement_website/server/controllers/users.js), line 76 and 95, the `req.body.points` would be a string when using `application/x-www-form-urlencoded`, causing the `typeof points !== 'number'` check always fails. 

Maybe try `parseInt(req.body.points)`.

**Comment by gcobcqwe** [comment]
Thanks for ur issue. After checking the SPEC and discussing it with @chuanchan1116, we still use `application/json` rather than  `application/x-www-form-urlencoded` .

**Comment by s3131212** [comment]
Glad to hear from you, and thanks for your information. I'll close the issue since there is nothing to be fixed.
